### ISSUE TITLE
Auto mode does not work on windows servers 2012R2/2016

### ISSUE THREAD

**Issue by matveevandrey** [SpookOz/zabbix-wininventory#2]
On Windows Servers 2012R2/2016 execution of:
`powershell.exe -NoProfile -ExecutionPolicy Bypass -command Invoke-WebRequest -Uri https://git.io/JUTv4 -OutFile $Env:Programfiles\'Zabbix Agent\plugins\get-inventory-v5.ps1'
`

fails with:

```
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
строка:1 знак:1
+ Invoke-WebRequest -Uri https://git.io/JUTv4 -OutFile $Env:Programfiles\'Zabbix A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 

```

**Comment by matveevandrey** [comment]
Following command works on Windows Server 2012R2/2016/2019

`powershell.exe -NoProfile -ExecutionPolicy Bypass -command [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -Uri https://git.io/JUTv4 -OutFile ( New-Item -Path "$Env:Programfiles\'Zabbix Agent\plugins\get-inventory-v5.ps1'" -itemtype file -Force )`

**Comment by matveevandrey** [comment]
How ever this string could not be used as key in template(

Any ideas?

**Comment by matveevandrey** [comment]
The only way I've found so far is:
1. Set HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SchUseStrongCrypto to DWORD 0X00000001
and Windows: HKLM\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319\SchUseStrongCrypto to DWROD 0X00000001 via GPO 
2. Use standard download powershell command
` powershell.exe -NoProfile -ExecutionPolicy Bypass -command Invoke-WebRequest -Uri https://git.io/JUTv4 -OutFile ( New-Item -Path "$Env:Programfiles\'Zabbix Agent\plugins\get-inventory-v5.ps1'" -itemtype file -Force )`

**Comment by SpookOz** [comment]
Oh - I think I just answered a similar question of yours in the other thread. Yeah I suspect that command is too long. Do you know why that error is occurring in 2012/2016? Is it because github is using TLS 1.2 or something that is not supported in ealier versions od that PS cmdlet?

If so, maybe upgrading Powershell might work? I can't really see another workaround that wouldn't entail some significant changes. For example, you could host the file yourself and download it from a less secure location? Or you could deploy it using another method? Or you could even install CURL and use that to download it?

Come to think of it, you could completely disable that item in the template anyway. It's only needed to update the PS script from github if I ever make any changes to it. For security it might be a good idea to disable it anyway. In theory I could upload a malicious PS script (not that I would - but you're better off not putting your trust in a stranger!). Once the ps file is on your machine, you don't really need to update it. You could have it deployed to your machines as part of the Zabbix install. How do you currently deply the Zabbix clients?
